# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ppath < Formula
  desc "A command-line tool to pretty print your system's PATH environment variable"
  homepage "https://github.com/marwanhawari/ppath"
  version "0.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marwanhawari/ppath/releases/download/v0.0.3/ppath-v0.0.3-darwin-arm64.tar.gz"
      sha256 "d40add61bad5ef641bb712cde3994fce91809f2a703d8bb78acce50dece166fd"

      def install
        bin.install "ppath"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/ppath/releases/download/v0.0.3/ppath-v0.0.3-darwin-amd64.tar.gz"
      sha256 "6fa4ccdf5e9a0a5618815db71c291def066d5a7ea7e5ef1f4829d80b7cdbbe3c"

      def install
        bin.install "ppath"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marwanhawari/ppath/releases/download/v0.0.3/ppath-v0.0.3-linux-arm64.tar.gz"
      sha256 "e3bbe814837a21daebdf654fb7c6ca4209ff1fc56cd56df6f4b36dba001d3607"

      def install
        bin.install "ppath"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/ppath/releases/download/v0.0.3/ppath-v0.0.3-linux-amd64.tar.gz"
      sha256 "ffdf64035ac37391b03fc16145badbd30bfb47c5f2dbcf4b7ea3282ce0fcd4d3"

      def install
        bin.install "ppath"
      end
    end
  end
end
