# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stew < Formula
  desc "An independent package manager for compiled binaries"
  homepage "https://github.com/marwanhawari/stew"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/stew/releases/download/v0.6.0/stew-v0.6.0-darwin-amd64.tar.gz"
      sha256 "a36043d3277849d153c208060e68127135bbf2081a5631a119c4ccd92773f25f"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marwanhawari/stew/releases/download/v0.6.0/stew-v0.6.0-darwin-arm64.tar.gz"
      sha256 "08eabadd10d54658afd65febd645577d47f1fb59dccc45c9db234994169739af"

      def install
        bin.install "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marwanhawari/stew/releases/download/v0.6.0/stew-v0.6.0-linux-amd64.tar.gz"
        sha256 "0a01b8a57ab219a3a1730d3d0a16f4cdda2e5c83626d57ab0455e995460eeb4f"

        def install
          bin.install "stew"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/marwanhawari/stew/releases/download/v0.6.0/stew-v0.6.0-linux-arm64.tar.gz"
        sha256 "00392c503f08d8dfac38d0f35672337db032ea8e0500ba46c4884f3fde4bcf92"

        def install
          bin.install "stew"
        end
      end
    end
  end
end
