# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stew < Formula
  desc "An independent package manager for compiled binaries"
  homepage "https://github.com/marwanhawari/stew"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/stew/releases/download/v0.4.0/stew-v0.4.0-darwin-amd64.tar.gz"
      sha256 "eb6ca5321867b4af5595ab36ef4f27fb7eb068b0849b22a8d05d3cff0ccf3c30"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/marwanhawari/stew/releases/download/v0.4.0/stew-v0.4.0-darwin-arm64.tar.gz"
      sha256 "cb44410bdd18089512a5adf55f8ec2c411e54bf981e3d513cfab7c7c85f2d475"

      def install
        bin.install "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/stew/releases/download/v0.4.0/stew-v0.4.0-linux-amd64.tar.gz"
      sha256 "2cd5d31fcf8b1999e46e6c4144ab9cdab9cb75c36b9e07a97fb2a6df8ea0e356"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marwanhawari/stew/releases/download/v0.4.0/stew-v0.4.0-linux-arm64.tar.gz"
      sha256 "b790b04fa571b07918d213b6d0a4babc5af059ae3cefa074ba357e102986900f"

      def install
        bin.install "stew"
      end
    end
  end
end
