# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stew < Formula
  desc "An independent package manager for compiled binaries"
  homepage "https://github.com/marwanhawari/stew"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/marwanhawari/stew/releases/download/v0.3.0/stew-darwin-arm64"
      sha256 "95a9d6a7cc2ab5b9e92b8e0bac646139bee42e1ed91b61b8ae1389fdd92405da"

      def install
        bin.install "stew-darwin-arm64" => "stew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/stew/releases/download/v0.3.0/stew-darwin-amd64"
      sha256 "04216cf6b326ebc973fdad003f015e30e9c04f810e25f7dd6fa9f0756894385d"

      def install
        bin.install "stew-darwin-amd64" => "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/marwanhawari/stew/releases/download/v0.3.0/stew-linux-amd64"
      sha256 "e64548f83ef34a6c7267d6edfbd0b913e3ee0436cd6fd39a218a3196cf54c0c9"

      def install
        bin.install "stew-linux-amd64" => "stew"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/marwanhawari/stew/releases/download/v0.3.0/stew-linux-arm64"
      sha256 "0ee8c875a235c37b40c653456976af2c42e02f8450f2722274fa247ad1584b6c"

      def install
        bin.install "stew-linux-arm64" => "stew"
      end
    end
  end
end
